services:
  # 1. שירות הבקאנד (Spring Boot - Java)
  - type: web
    name: back-clicker-service
    runtime: java
    repo: https://github.com/rp0556797395-gif/special-thing
    branch: main
    rootDir: BackClicker
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar
    envVars:
      - key: DB_URL
      - key: DB_USERNAME
      - key: DB_PASSWORD

  # 2. שירות הפרונטאנד (Static Site - Node)
  # 2. שירות הפרונטאנד (Next.js - Node)
  - type: web
    name: front-clicker-service
    runtime: node
    repo: https://github.com/rp0556797395-gif/special-thing
    branch: main
    rootDir: FrontClicker
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production