spring.application.name=Parking

# ===============================
# EMAIL SETTINGS (?????? ????? ????)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# ?? ????? ????? ??? ??????? ?????? ???:
spring.mail.username=YOUR_EMAIL@gmail.com
spring.mail.password=cfff phwh ptzj ygci
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# DATABASE CONNECTION (????? ?????????)
# ===============================
//aws-1-ap-southeast-2.pooler.supabase.com
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# ?????? ????? ?????? ???????? (Hibernate)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true