-- קומה 1 - תור A
INSERT INTO PARKING (FLOOR, ROW_LETTER, LOCATION, IS_OCCUPIED, PRICE_PER_HOUR) VALUES (1, 'A', '1A-01', FALSE, 15.0);
INSERT INTO PARKING (FLOOR, ROW_LETTER, LOCATION, IS_OCCUPIED, PRICE_PER_HOUR) VALUES (1, 'A', '1A-02', FALSE, 15.0);
INSERT INTO PARKING (FLOOR, ROW_LETTER, LOCATION, IS_OCCUPIED, PRICE_PER_HOUR) VALUES (1, 'A', '1A-03', FALSE, 15.0);
-- קומה 1 - תור B
INSERT INTO PARKING (FLOOR, ROW_LETTER, LOCATION, IS_OCCUPIED, PRICE_PER_HOUR) VALUES (1, 'B', '1B-01', FALSE, 15.0);
INSERT INTO PARKING (FLOOR, ROW_LETTER, LOCATION, IS_OCCUPIED, PRICE_PER_HOUR) VALUES (1, 'B', '1B-02', FALSE, 15.0);
INSERT INTO PARKING (FLOOR, ROW_LETTER, LOCATION, IS_OCCUPIED, PRICE_PER_HOUR) VALUES (1, 'B', '1B-03', FALSE, 15.0);

-- קומה 2 - תור A
INSERT INTO PARKING (FLOOR, ROW_LETTER, LOCATION, IS_OCCUPIED, PRICE_PER_HOUR) VALUES (2, 'A', '2A-01', FALSE, 12.0);
INSERT INTO PARKING (FLOOR, ROW_LETTER, LOCATION, IS_OCCUPIED, PRICE_PER_HOUR) VALUES (2, 'A', '2A-02', FALSE, 12.0);
INSERT INTO PARKING (FLOOR, ROW_LETTER, LOCATION, IS_OCCUPIED, PRICE_PER_HOUR) VALUES (2, 'A', '2A-03', FALSE, 12.0);
-- קומה 2 - תור B
INSERT INTO PARKING (FLOOR, ROW_LETTER, LOCATION, IS_OCCUPIED, PRICE_PER_HOUR) VALUES (2, 'B', '2B-01', FALSE, 12.0);
INSERT INTO PARKING (FLOOR, ROW_LETTER, LOCATION, IS_OCCUPIED, PRICE_PER_HOUR) VALUES (2, 'B', '2B-02', FALSE, 12.0);

-- קומה 3 - תור C (למשל חניות VIP)
INSERT INTO PARKING (FLOOR, ROW_LETTER, LOCATION, IS_OCCUPIED, PRICE_PER_HOUR) VALUES (3, 'C', '3C-01', FALSE, 20.0);
INSERT INTO PARKING (FLOOR, ROW_LETTER, LOCATION, IS_OCCUPIED, PRICE_PER_HOUR) VALUES (3, 'C', '3C-02', FALSE, 20.0);
INSERT INTO PARKING (FLOOR, ROW_LETTER, LOCATION, IS_OCCUPIED, PRICE_PER_HOUR) VALUES (3, 'C', '3C-03', FALSE, 20.0);